// Code generated by goyacc -o queryparser.go -p Query queryparser.y. DO NOT EDIT.

//line queryparser.y:5

package parser

import __yyfmt__ "fmt"

//line queryparser.y:6

import (
	"github.com/publicocean0/queryparser/common"
	"regexp"
	"strconv"
)

//line queryparser.y:23
type QuerySymType struct {
	yys   int
	expr  common.Expression
	cond  common.Condition
	token common.Token
}

const IDENT = 57346
const STRING = 57347
const INT = 57348
const FLOAT = 57349
const BOOL = 57350
const EQ = 57351
const NEQ = 57352
const LT = 57353
const GT = 57354
const LTE = 57355
const GTE = 57356
const LPAREN = 57357
const RPAREN = 57358
const AND = 57359
const NOT = 57360
const OR = 57361
const LIKE = 57362
const NLIKE = 57363
const DATE = 57364
const DATETIME = 57365
const TIME = 57366
const DURATION = 57367

var QueryToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"STRING",
	"INT",
	"FLOAT",
	"BOOL",
	"EQ",
	"NEQ",
	"LT",
	"GT",
	"LTE",
	"GTE",
	"LPAREN",
	"RPAREN",
	"AND",
	"NOT",
	"OR",
	"LIKE",
	"NLIKE",
	"DATE",
	"DATETIME",
	"TIME",
	"DURATION",
}
var QueryStatenames = [...]string{}

const QueryEofCode = 1
const QueryErrCode = 2
const QueryInitialStackSize = 16

//line queryparser.y:727
/*  start  of  programs  */

type QueryLexerImpl struct {
	src       string
	pos       int
	re        *regexp.Regexp
	Exception *common.Exception
	AST       common.Expression
}

func (l *QueryLexerImpl) PositionedError(pos int, msg string) {
	l.Exception = &common.Exception{}

	s := l.src[pos:]
	l.Exception.Init(pos, msg+" at "+s)
}

func (l *QueryLexerImpl) Init(src string) {
	l.src = src
	l.pos = 0
	l.re = regexp.MustCompile(`^((?P<op>((OR)|(NOT)|(AND)))|(?P<comp>((\!\=)|(\!\~)|(\<\=)|(\>\=)|(\=)|(\~)|(\>)|(\<)))|(?P<bool>((true)|(false)))|(?P<string>\"(?:[^"\\]|\\.)*\")|(?P<ident>[A-Za-z]\w*)|(?P<time>((\d{4}\-\d{2}\-\d{2})(T(\d{1,2}\:\d{2}((\:\d{2}(\:\d{2})?)?)(([-+]\d{2}\:\d{2})|Z)?))?)|([-+]?\d{1,2}\:\d{2}((\:\d{2}(\:\d{2})?)?)(([-+]\d{2}\:\d{2})|Z)?))|(?P<number>([-+]?\d+)(\.\d+)?))`)
}

func (l *QueryLexerImpl) Lex(lval *QuerySymType) int {
	if l.Exception != nil {
		return -1
	}
	var t int = -1
	len := len(l.src)
	// remove all spaces on the left
	for l.pos < len && (l.src[l.pos] == ' ' || l.src[l.pos] == '\t') {
		l.pos++

	}
	if l.pos == len {
		return -1
	}

	if l.src[l.pos] == '(' {
		t = LPAREN
		lval.token = common.Token{Position: l.pos, Token: t, Literal: "("}
		l.pos++
		return t
	} else if l.src[l.pos] == ')' {
		t = RPAREN
		lval.token = common.Token{Position: l.pos, Token: t, Literal: ")"}
		l.pos++
		return t
	}
	//find the leftmost token (and its subtokens)
	result := l.re.FindSubmatchIndex([]byte(l.src[l.pos:]))
	if result == nil {
		return -1
	}
	for pairIndex := 2; t == -1 && pairIndex < 84; pairIndex += 2 {

		rstart := result[pairIndex]
		if rstart != -1 {
			start := l.pos + result[pairIndex]
			switch pairIndex {
			// comparator
			case 18:
				t = NEQ
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: "!="}
				break
			case 20:
				t = NLIKE
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: "!~"}
				break
			case 22:
				t = LTE
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: "<="}
				break
			case 24:
				t = GTE
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: ">="}
				break
			case 26:
				t = EQ
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: "="}
				break
			case 28:
				t = LIKE
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: "~"}
				break
			case 30:
				t = GT
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: ">"}
				break
			case 32:
				t = LT
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: "<"}
				break
			case 78:
				if result[82] != -1 {
					t = FLOAT
				} else {
					t = INT
				}
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: l.src[start : l.pos+result[pairIndex+1]]}
				break
				// string
			case 42: //SHIFT
				t = STRING
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: l.src[start+1 : l.pos+result[pairIndex+1]-1]}
				break
			case 8:
				t = OR
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: "OR"}
				break
			case 10:
				t = NOT
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: "NOT"}
				break
			case 12:
				t = AND
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: "AND"}
				break
			case 36:
				t = BOOL
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: l.src[start : l.pos+result[pairIndex+1]]}
				break
			case 44: // gia' sfhittato
				t = IDENT
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: l.src[start : l.pos+result[pairIndex+1]]}
				break
			case 66:
				ch := l.src[l.pos+result[66]]
				if ch == '+' || ch == '-' {
					t = DURATION
				} else {
					t = TIME
				}

				s := ""
				var index = pairIndex + 1
				if result[70] == -1 {
					s += ":00"
					if result[74] != -1 {
						s += l.src[l.pos+result[74] : l.pos+result[75]]
						index = 74
					}
				}
				if t == TIME {
					if result[74] == -1 {
						s += "+00:00"
					} else if l.src[result[74]] == 'Z' {
						index--
						s += "+00:00"
					}
				} else {
					if result[74] != -1 {
						return -1
					}
				}
				lval.token = common.Token{Position: l.pos + start, Token: t, Literal: l.src[start:l.pos+result[index]] + s}
				break
			case 48:
				s := ""
				if result[52] != -1 {
					t = DATETIME
					var index = pairIndex + 1
					if result[58] == -1 {
						s = ":00"
						if result[62] != -1 {
							s += l.src[l.pos+result[62] : l.pos+result[63]]
							index = 62
						}
					}
					if result[62] == -1 {
						s += "+00:00"
					} else if l.src[result[62]] == 'Z' {
						index--
						s += "+00:00"
					}

					lval.token = common.Token{Position: l.pos + start, Token: t, Literal: l.src[start:l.pos+result[index]] + s}

				} else {
					t = DATE
					s += "T00:00:00+00:00"
					lval.token = common.Token{Position: l.pos + start, Token: t, Literal: l.src[start:l.pos+result[pairIndex+1]] + s}
				}

				break

			}
			if t != -1 {
				l.pos += result[pairIndex+1]
				if l.pos != len && l.src[l.pos] != ' ' {
					t = -1
					l.pos -= result[pairIndex+1]
					l.PositionedError(l.pos, "invalid token")
					return t
				}
			}

		}

	}

	return t
}
func (l *QueryLexerImpl) Error(e string) {
	l.Exception = &common.Exception{}

	s := l.src[l.pos:]
	l.Exception.Init(l.pos, e+" at "+s)

}

//line yacctab:1
var QueryExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const QueryPrivate = 57344

const QueryLast = 91

var QueryAct = [...]int{

	77, 79, 80, 78, 69, 71, 72, 70, 61, 63,
	64, 62, 53, 55, 56, 54, 7, 81, 82, 83,
	84, 73, 74, 75, 76, 65, 66, 67, 68, 57,
	58, 59, 60, 45, 47, 48, 46, 37, 39, 40,
	38, 29, 31, 32, 30, 21, 23, 24, 22, 2,
	49, 50, 51, 52, 41, 42, 43, 44, 33, 34,
	35, 36, 25, 26, 27, 28, 10, 11, 12, 13,
	14, 15, 20, 6, 5, 7, 0, 16, 17, 6,
	0, 7, 1, 0, 0, 3, 8, 9, 4, 18,
	19,
}
var QueryPact = [...]int{

	70, 62, -1000, 70, 70, 57, 70, 70, 56, -1000,
	40, 36, 32, 28, 7, 3, -1, -5, -3, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000,
}
var QueryPgo = [...]int{

	0, 82, 49,
}
var QueryR1 = [...]int{

	0, 1, 1, 1, 1, 1, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
}
var QueryR2 = [...]int{

	0, 1, 3, 3, 3, 2, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
}
var QueryChk = [...]int{

	-1000, -1, -2, 15, 18, 4, 17, 19, -1, -1,
	9, 10, 11, 12, 13, 14, 20, 21, -1, -1,
	16, 5, 8, 6, 7, 22, 23, 24, 25, 5,
	8, 6, 7, 22, 23, 24, 25, 5, 8, 6,
	7, 22, 23, 24, 25, 5, 8, 6, 7, 22,
	23, 24, 25, 5, 8, 6, 7, 22, 23, 24,
	25, 5, 8, 6, 7, 22, 23, 24, 25, 5,
	8, 6, 7, 22, 23, 24, 25, 5, 8, 6,
	7, 22, 23, 24, 25,
}
var QueryDef = [...]int{

	0, -2, 1, 0, 0, 0, 0, 0, 0, 5,
	0, 0, 0, 0, 0, 0, 0, 0, 3, 4,
	2, 6, 14, 22, 28, 38, 39, 40, 41, 7,
	15, 25, 29, 42, 43, 44, 45, 8, 16, 31,
	33, 46, 47, 48, 49, 9, 17, 30, 32, 50,
	51, 52, 53, 10, 18, 35, 37, 54, 55, 56,
	57, 11, 19, 34, 36, 58, 59, 60, 61, 12,
	20, 23, 26, 62, 63, 64, 68, 13, 21, 24,
	27, 65, 66, 67, 69,
}
var QueryTok1 = [...]int{

	1,
}
var QueryTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25,
}
var QueryTok3 = [...]int{
	0,
}

var QueryErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	QueryDebug        = 0
	QueryErrorVerbose = false
)

type QueryLexer interface {
	Lex(lval *QuerySymType) int
	Error(s string)
}

type QueryParser interface {
	Parse(QueryLexer) int
	Lookahead() int
}

type QueryParserImpl struct {
	lval  QuerySymType
	stack [QueryInitialStackSize]QuerySymType
	char  int
}

func (p *QueryParserImpl) Lookahead() int {
	return p.char
}

func QueryNewParser() QueryParser {
	return &QueryParserImpl{}
}

const QueryFlag = -1000

func QueryTokname(c int) string {
	if c >= 1 && c-1 < len(QueryToknames) {
		if QueryToknames[c-1] != "" {
			return QueryToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func QueryStatname(s int) string {
	if s >= 0 && s < len(QueryStatenames) {
		if QueryStatenames[s] != "" {
			return QueryStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func QueryErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !QueryErrorVerbose {
		return "syntax error"
	}

	for _, e := range QueryErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + QueryTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := QueryPact[state]
	for tok := TOKSTART; tok-1 < len(QueryToknames); tok++ {
		if n := base + tok; n >= 0 && n < QueryLast && QueryChk[QueryAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if QueryDef[state] == -2 {
		i := 0
		for QueryExca[i] != -1 || QueryExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; QueryExca[i] >= 0; i += 2 {
			tok := QueryExca[i]
			if tok < TOKSTART || QueryExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if QueryExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += QueryTokname(tok)
	}
	return res
}

func Querylex1(lex QueryLexer, lval *QuerySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = QueryTok1[0]
		goto out
	}
	if char < len(QueryTok1) {
		token = QueryTok1[char]
		goto out
	}
	if char >= QueryPrivate {
		if char < QueryPrivate+len(QueryTok2) {
			token = QueryTok2[char-QueryPrivate]
			goto out
		}
	}
	for i := 0; i < len(QueryTok3); i += 2 {
		token = QueryTok3[i+0]
		if token == char {
			token = QueryTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = QueryTok2[1] /* unknown char */
	}
	if QueryDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", QueryTokname(token), uint(char))
	}
	return char, token
}

func QueryParse(Querylex QueryLexer) int {
	return QueryNewParser().Parse(Querylex)
}

func (Queryrcvr *QueryParserImpl) Parse(Querylex QueryLexer) int {
	var Queryn int
	var QueryVAL QuerySymType
	var QueryDollar []QuerySymType
	_ = QueryDollar // silence set and not used
	QueryS := Queryrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Querystate := 0
	Queryrcvr.char = -1
	Querytoken := -1 // Queryrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Querystate = -1
		Queryrcvr.char = -1
		Querytoken = -1
	}()
	Queryp := -1
	goto Querystack

ret0:
	return 0

ret1:
	return 1

Querystack:
	/* put a state and value onto the stack */
	if QueryDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", QueryTokname(Querytoken), QueryStatname(Querystate))
	}

	Queryp++
	if Queryp >= len(QueryS) {
		nyys := make([]QuerySymType, len(QueryS)*2)
		copy(nyys, QueryS)
		QueryS = nyys
	}
	QueryS[Queryp] = QueryVAL
	QueryS[Queryp].yys = Querystate

Querynewstate:
	Queryn = QueryPact[Querystate]
	if Queryn <= QueryFlag {
		goto Querydefault /* simple state */
	}
	if Queryrcvr.char < 0 {
		Queryrcvr.char, Querytoken = Querylex1(Querylex, &Queryrcvr.lval)
	}
	Queryn += Querytoken
	if Queryn < 0 || Queryn >= QueryLast {
		goto Querydefault
	}
	Queryn = QueryAct[Queryn]
	if QueryChk[Queryn] == Querytoken { /* valid shift */
		Queryrcvr.char = -1
		Querytoken = -1
		QueryVAL = Queryrcvr.lval
		Querystate = Queryn
		if Errflag > 0 {
			Errflag--
		}
		goto Querystack
	}

Querydefault:
	/* default state action */
	Queryn = QueryDef[Querystate]
	if Queryn == -2 {
		if Queryrcvr.char < 0 {
			Queryrcvr.char, Querytoken = Querylex1(Querylex, &Queryrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if QueryExca[xi+0] == -1 && QueryExca[xi+1] == Querystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Queryn = QueryExca[xi+0]
			if Queryn < 0 || Queryn == Querytoken {
				break
			}
		}
		Queryn = QueryExca[xi+1]
		if Queryn < 0 {
			goto ret0
		}
	}
	if Queryn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Querylex.Error(QueryErrorMessage(Querystate, Querytoken))
			Nerrs++
			if QueryDebug >= 1 {
				__yyfmt__.Printf("%s", QueryStatname(Querystate))
				__yyfmt__.Printf(" saw %s\n", QueryTokname(Querytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Queryp >= 0 {
				Queryn = QueryPact[QueryS[Queryp].yys] + QueryErrCode
				if Queryn >= 0 && Queryn < QueryLast {
					Querystate = QueryAct[Queryn] /* simulate a shift of "error" */
					if QueryChk[Querystate] == QueryErrCode {
						goto Querystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if QueryDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", QueryS[Queryp].yys)
				}
				Queryp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if QueryDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", QueryTokname(Querytoken))
			}
			if Querytoken == QueryEofCode {
				goto ret1
			}
			Queryrcvr.char = -1
			Querytoken = -1
			goto Querynewstate /* try again in the same state */
		}
	}

	/* reduction by production Queryn */
	if QueryDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Queryn, QueryStatname(Querystate))
	}

	Querynt := Queryn
	Querypt := Queryp
	_ = Querypt // guard against "declared and not used"

	Queryp -= QueryR2[Queryn]
	// Queryp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Queryp+1 >= len(QueryS) {
		nyys := make([]QuerySymType, len(QueryS)*2)
		copy(nyys, QueryS)
		QueryS = nyys
	}
	QueryVAL = QueryS[Queryp+1]

	/* consult goto table to find next state */
	Queryn = QueryR1[Queryn]
	Queryg := QueryPgo[Queryn]
	Queryj := Queryg + QueryS[Queryp].yys + 1

	if Queryj >= QueryLast {
		Querystate = QueryAct[Queryg]
	} else {
		Querystate = QueryAct[Queryj]
		if QueryChk[Querystate] != -Queryn {
			Querystate = QueryAct[Queryg]
		}
	}
	// dummy call; replaced with literal code
	switch Querynt {

	case 1:
		QueryDollar = QueryS[Querypt-1 : Querypt+1]
//line queryparser.y:63
		{
			QueryVAL.expr = QueryDollar[1].cond
			Querylex.(*QueryLexerImpl).AST = QueryVAL.expr

		}
	case 2:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:69
		{
			QueryVAL.expr = common.SubExpression{Expr: QueryDollar[2].expr}
			Querylex.(*QueryLexerImpl).AST = QueryVAL.expr

		}
	case 3:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:75
		{
			QueryVAL.expr = common.BiExpression{BooleanOperator: QueryDollar[2].token, Left: QueryDollar[1].expr, Right: QueryDollar[3].expr}
			Querylex.(*QueryLexerImpl).AST = QueryVAL.expr

		}
	case 4:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:80
		{
			QueryVAL.expr = common.BiExpression{BooleanOperator: QueryDollar[2].token, Left: QueryDollar[1].expr, Right: QueryDollar[3].expr}
			Querylex.(*QueryLexerImpl).AST = QueryVAL.expr
		}
	case 5:
		QueryDollar = QueryS[Querypt-2 : Querypt+1]
//line queryparser.y:83
		{
			QueryVAL.expr = common.BiExpression{BooleanOperator: QueryDollar[1].token, Left: QueryDollar[2].expr}
			Querylex.(*QueryLexerImpl).AST = QueryVAL.expr
		}
	case 6:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:91
		{
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: QueryDollar[3].token.Literal}}
		}
	case 7:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:95
		{
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: QueryDollar[3].token.Literal}}
		}
	case 8:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:99
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 9:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:105
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 10:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:111
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 11:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:117
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 12:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:123
		{
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: QueryDollar[3].token.Literal}}
		}
	case 13:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:127
		{
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: QueryDollar[3].token.Literal}}
		}
	case 14:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:131
		{
			b, e := strconv.ParseBool(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: b}}
		}
	case 15:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:143
		{
			b, e := strconv.ParseBool(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: b}}
		}
	case 16:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:155
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 17:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:161
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 18:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:167
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 19:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:173
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 20:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:179
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 21:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:185
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 22:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:191
		{
			i, e := strconv.ParseInt(QueryDollar[3].token.Literal, 10, 64)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: i}}

		}
	case 23:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:204
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 24:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:210
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 25:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:216
		{
			i, e := strconv.ParseInt(QueryDollar[3].token.Literal, 10, 64)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: i}}

		}
	case 26:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:229
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 27:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:235
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 28:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:241
		{
			f, e := strconv.ParseFloat(QueryDollar[3].token.Literal, 64)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: f}}

		}
	case 29:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:254
		{
			f, e := strconv.ParseFloat(QueryDollar[3].token.Literal, 64)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: f}}

		}
	case 30:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:267
		{
			i, e := strconv.ParseInt(QueryDollar[3].token.Literal, 10, 64)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: i}}

		}
	case 31:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:280
		{
			i, e := strconv.ParseInt(QueryDollar[3].token.Literal, 10, 64)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: i}}

		}
	case 32:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:293
		{
			f, e := strconv.ParseFloat(QueryDollar[3].token.Literal, 64)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: f}}

		}
	case 33:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:306
		{
			f, e := strconv.ParseFloat(QueryDollar[3].token.Literal, 64)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: f}}

		}
	case 34:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:319
		{
			i, e := strconv.ParseInt(QueryDollar[3].token.Literal, 10, 64)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: i}}

		}
	case 35:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:332
		{
			i, e := strconv.ParseInt(QueryDollar[3].token.Literal, 10, 64)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: i}}

		}
	case 36:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:345
		{
			f, e := strconv.ParseFloat(QueryDollar[3].token.Literal, 64)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: f}}

		}
	case 37:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:358
		{
			f, e := strconv.ParseFloat(QueryDollar[3].token.Literal, 64)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: f}}

		}
	case 38:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:371
		{
			t, e := common.ParseDate(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 39:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:384
		{
			t, e := common.ParseDateTime(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 40:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:397
		{
			t, e := common.ParseTime(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 41:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:410
		{
			t, e := common.ParseDuration(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 42:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:423
		{
			t, e := common.ParseDate(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 43:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:436
		{
			t, e := common.ParseDateTime(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 44:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:449
		{
			t, e := common.ParseTime(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 45:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:462
		{
			t, e := common.ParseDuration(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 46:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:475
		{
			t, e := common.ParseDate(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 47:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:488
		{
			t, e := common.ParseDateTime(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 48:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:501
		{
			t, e := common.ParseTime(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 49:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:514
		{
			t, e := common.ParseDuration(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 50:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:527
		{
			t, _ := common.ParseDate(QueryDollar[3].token.Literal)
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 51:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:533
		{
			t, e := common.ParseDateTime(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 52:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:546
		{
			t, e := common.ParseTime(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 53:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:559
		{
			t, e := common.ParseDuration(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 54:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:572
		{
			t, e := common.ParseDate(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 55:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:585
		{
			t, e := common.ParseDateTime(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 56:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:598
		{
			t, e := common.ParseTime(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 57:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:611
		{
			t, e := common.ParseDuration(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 58:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:624
		{
			t, e := common.ParseDate(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 59:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:637
		{
			t, e := common.ParseDateTime(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 60:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:650
		{
			t, e := common.ParseTime(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 61:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:663
		{
			t, e := common.ParseDuration(QueryDollar[3].token.Literal)
			if e != nil {
				ql, _ := Querylex.(*QueryLexerImpl)
				ql.PositionedError(QueryDollar[3].token.Position, e.Error())

				break
			}
			QueryVAL.cond = common.Condition{Variable: QueryDollar[1].token, Comparator: QueryDollar[2].token, Value: common.TokenValue{Token: QueryDollar[3].token.Token, Content: *t}}

		}
	case 62:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:675
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 63:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:681
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 64:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:687
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 65:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:693
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 66:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:699
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 67:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:705
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 68:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:711
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	case 69:
		QueryDollar = QueryS[Querypt-3 : Querypt+1]
//line queryparser.y:718
		{
			ql, _ := Querylex.(*QueryLexerImpl)
			ql.PositionedError(QueryDollar[2].token.Position, "invalid operator")
			break
		}
	}
	goto Querystack /* stack new state and value */
}
